name: build with cargo in a container

on: workflow_dispatch

jobs:
  test-the-workaround:
    runs-on: ubuntu-latest
    steps:
      - uses: JonasAlfredsson/docker-on-tmpfs@v1
        with:
          tmpfs_size: 3
          swap_size: 6
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install -y qemu-user-static
      - uses: redhat-actions/buildah-build@v2
        with:
          platforms: linux/arm
          containerfiles: |
            ./Dockerfile
          image: test
