name: build with cargo in a container

on: workflow_dispatch

jobs:
  armv7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install -y qemu-user-static
      - uses: redhat-actions/buildah-build@v2
        with:
          platforms: linux/arm
          containerfiles: |
            ./Dockerfile
          image: cargo-in-a-container
  arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install -y qemu-user-static
      - uses: redhat-actions/buildah-build@v2
        with:
          platforms: linux/arm64
          containerfiles: |
            ./Dockerfile
          image: cargo-in-a-container
